//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JhulayLal_Enterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBillDetail
    {
        public int Id { get; set; }
        public Nullable<int> Bags { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> BillID { get; set; }
    
        public virtual AspNetBill AspNetBill { get; set; }
    }
}
